### ISSUE TITLE
1.18.x support?

### ISSUE THREAD

**Issue by RareMaker50** [lokka30/BetterCommandSpy#8]
Wondering if there is 1.18.x support and if there isn't when it would be implemented?

**Comment by lokka30** [comment]
Hi! I'm very sorry, no idea how I didn't reply to this.. that's a rare thing!

BetterCommandSpy has supported 1.18 since the version came out. I believe there may have been a compatibility checker previously which complained about it (which I have since removed), though I doubt BetterCommandSpy will break until long into the future of the game.
